name: Deploy Monorepo

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
    steps:
      - uses: actions/checkout@v4

      # Authenticate to GCP
      - uses: google-github-actions/auth@v3
        with:
          project_id: 'david-web-app-development'
          workload_identity_provider: 'projects/555157153482/locations/global/workloadIdentityPools/github-actions/providers/github-stock-screener'

      # Install Node
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      # Build frontend
      - run: |
          cd frontend
          npm ci
          npm run build

      # Deploy to Cloud Storage
      - run: |
          gsutil -m rsync -r frontend/dist gs://my-frontend-bucket
          gsutil -m acl set -R -a public-read gs://my-frontend-bucket

  backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: frontend   # wait for frontend first
    steps:
      - uses: actions/checkout@v4

      # Authenticate to GCP
      - uses: google-github-actions/auth@v3
        with:
          project_id: 'david-web-app-development'
          workload_identity_provider: projects/555157153482/locations/global/workloadIdentityPools/github-actions/providers/github-stock-screener

      # Build Docker image
      - run: |
          cd backend
          docker build -t us-central1-docker.pkg.dev/david-web-app-development/stock-screener/backend:latest .

      # Push to Artifact Registry
      - run: |
          docker push us-central1-docker.pkg.dev/david-web-app-development/stock-screener/backend:latest

      # Deploy to Cloud Run
      - run: |
          gcloud run deploy stock-screener-backend \
            --image us-central1-docker.pkg.dev/david-web-app-development/stock-screener/backend:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
