name: Deploy Monorepo

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          project_id: 'david-web-app-development'
          workload_identity_provider: 'projects/555157153482/locations/global/workloadIdentityPools/github-ddavidd-lim/providers/github-stock-screener'
          service_account: 'github-actions@david-web-app-development.iam.gserviceaccount.com'
      
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Build frontend
        run: |
          cd frontend
          pnpm install --frozen-lockfile
          pnpm run build
        env: 
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy to Cloud Storage
        run: |
          gcloud storage rsync --recursive frontend/dist gs://wavidwim.com

  backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: frontend   # wait for frontend first
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          project_id: 'david-web-app-development'
          workload_identity_provider: 'projects/555157153482/locations/global/workloadIdentityPools/github-ddavidd-lim/providers/github-stock-screener'
          service_account: 'github-actions@david-web-app-development.iam.gserviceaccount.com'

      - name: Build Docker image
        run: |
          cd backend
          docker build -t us-west2-docker.pkg.dev/david-web-app-development/stock-screener/backend:latest .

      - name: Authenticate Docker
        run: gcloud auth configure-docker us-west2-docker.pkg.dev

      - name: Push to Artifact Registry
        run: |
          docker push us-west2-docker.pkg.dev/david-web-app-development/stock-screener/backend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy stock-screener-backend \
            --image us-west2-docker.pkg.dev/david-web-app-development/stock-screener/backend:latest \
            --region us-west2 \
            --service-account cloud-run-backend@david-web-app-development.iam.gserviceaccount.com \
            --platform managed \
            --allow-unauthenticated
